#!/bin/zsh

set keyseq-timeout 0   # no key delays
setopt COMBINING_CHARS # better paste for emojis

# basic programs
export EDITOR="nvim"
export VISUAL="nvim"

# Colored LS output
export CLICOLOR=true

if command -v bat >/dev/null 2>&1; then
  export PAGER="bat"
  export MANPAGER="sh -c 'col -bx | bat -l man -p'"
  export FZF_CTRL_T_OPTS="--preview 'bat --line-range :50 {}'"
else
  export PAGER="less"
  export MANPAGER="less"
fi

# basic exports
export XDG_CONFIG_HOME="$HOME/.config"
export TMUX_CONF="$XDG_CONFIG_HOME/tmux/tmux.conf"
export DOTFILES="$HOME/.dotfiles"

# history
source <(fzf --zsh 2>/dev/null)
setopt hist_ignore_all_dups
setopt share_history
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000

# vi-mode - must be set before prompt
source $XDG_CONFIG_HOME/zsh/vi-mode.sh

# prompt
source $XDG_CONFIG_HOME/spaceship-prompt/spaceship.zsh
SPACESHIP_PROMPT_ORDER=(dir git exec_time async line_sep jobs exit_code sudo mode char)

# custom commands
source $XDG_CONFIG_HOME/zsh/alias.sh
source $XDG_CONFIG_HOME/zsh/atsign.sh
source $XDG_CONFIG_HOME/zsh/commands.sh

case "$(uname)" in
Darwin)
  eval "$(/opt/homebrew/bin/brew shellenv)"
  ;;
Linux)
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
  ;;
esac

export HOMEBREW_NO_ENV_HINTS=true
FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
[[ -f $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]] && source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Programming language setup
source $XDG_CONFIG_HOME/zsh/lang.sh

# Final setup of zsh completion
autoload -Uz compinit
compinit

# Export last so it's prioritized over other paths
export PATH="$HOME/.local/bin:$PATH"
