#!/bin/zsh

# zsh options
set keyseq-timeout 0   # no key delays
setopt COMBINING_CHARS # better paste for emojis

setopt auto_cd
setopt auto_pushd
setopt pushd_ignore_dups

setopt hist_ignore_all_dups
setopt inc_append_history
setopt share_history
setopt extended_history

# basic programs
export EDITOR="nvim"
export VISUAL="nvim"

# Pagers
export LESS='--mouse'
if command -v bat >/dev/null 2>&1; then
  export PAGER="bat"
  export MANPAGER="sh -c 'col -bx | bat -l man -p'"
  export FZF_CTRL_T_OPTS="--preview 'bat --line-range :50 {}'"
else
  export PAGER="less"
  export MANPAGER="less"
fi

# basic exports
export CLICOLOR=true # Colored ls output
export XDG_CONFIG_HOME="$HOME/.config"
export TMUX_CONF="$XDG_CONFIG_HOME/tmux/tmux.conf"
export DOTFILES="$HOME/.dotfiles"
export JJ_CONFIG="$XDG_CONFIG_HOME/jj/config.toml"

# vi-mode - must be set before prompt
source $XDG_CONFIG_HOME/zsh/vi-mode.sh

# prompt
source $XDG_CONFIG_HOME/spaceship-prompt/spaceship.zsh
# SPACESHIP_PROMPT_ORDER=(dir git exec_time async line_sep jobs exit_code sudo mode char)
# disable git cuz jj
SPACESHIP_PROMPT_ORDER=(dir exec_time async line_sep jobs exit_code sudo mode char)

# custom commands
source $XDG_CONFIG_HOME/zsh/alias.sh
source $XDG_CONFIG_HOME/zsh/commands.sh

case "$(uname)" in
Darwin)
  eval "$(/opt/homebrew/bin/brew shellenv)"
  ;;
Linux)
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
  ;;
esac

export HOMEBREW_NO_ENV_HINTS=true
FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
[[ -f $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]] && source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# history
HISTFILE="$HOME/.local/state/zsh/main_history"
if [ -n "$TMUX" ]; then
  TMUXHISTFILE="$(tmux showenv -h hist_file | cut -d= -f2)"
  [ -n "$TMUXHISTFILE" ] && HISTFILE="$TMUXHISTFILE"
fi
source <(fzf --zsh 2>/dev/null)
HISTSIZE=10000
SAVEHIST=10000

# Programming language setup
source $XDG_CONFIG_HOME/zsh/lang.sh

# Final setup of zsh completion
autoload -Uz compinit
compinit

# jj completion
# if command -v jj 2>&1 >/dev/null; then
#   source <(jj util completion zsh)
# fi

# Export last so it's prioritized over other paths
export PATH="$HOME/.local/bin:$PATH"
