#!/bin/zsh

set keyseq-timeout 0 # no key delays
setopt COMBINING_CHARS # better paste for emojis

# basic programs
export EDITOR="nvim"
export VISUAL="nvim"

if command -v "bat" >/dev/null 2>&1; then
  export PAGER="bat"
  export MANPAGER="sh -c 'col -bx | bat -l man -p'"
  export FZF_CTRL_T_OPTS="--preview 'bat --line-range :50 {}'"
else
  export PAGER="less"
  export MANPAGER="less"
fi

# basic exports
export XDG_CONFIG_HOME="$HOME/.config"
export TMUX_CONF="$XDG_CONFIG_HOME/tmux/tmux.conf"
export DOTFILES="$HOME/.dotfiles"

# history
source <(fzf --zsh 2>/dev/null)
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000

# vi-mode - must be set before prompt
source $XDG_CONFIG_HOME/zsh/vi-mode.sh

# prompt
source $XDG_CONFIG_HOME/spaceship-prompt/spaceship.zsh
SPACESHIP_PROMPT_ORDER=(dir git exec_time async line_sep jobs exit_code sudo mode char)

# custom commands
source $XDG_CONFIG_HOME/zsh/alias.sh
source $XDG_CONFIG_HOME/zsh/atsign.sh
source $XDG_CONFIG_HOME/zsh/commands.sh

# setup brew and zsh features
if [ "$(uname)" = 'Darwin' ]; then
  if command -v brew >/dev/null 2>&1; then
    export PATH="/opt/homebrew/bin:$PATH"
    export HOMEBREW_NO_ENV_HINTS=true
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
    [[ -f $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]] && source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
  fi
fi

# Programming language setup
source $XDG_CONFIG_HOME/zsh/lang.sh

# Final setup of zsh completion
autoload -Uz compinit
compinit

# Export last so it's prioritized over other paths
export PATH="$HOME/.local/bin:$PATH"
