#!/bin/sh

command -v sway >/dev/null 2>&1 && [ "$(tty)" = "/dev/tty1" ] && {
  source $HOME/.config/env/sway
  if [ "$(uname)" = 'daedalus' ]; then
    source $HOME/.config/env/framework
  fi
  exec sway
}
PATH="$PATH:$HOME/.local/bin"
