# vim:set ft=tmux:
# plugins
setenv -g HOME "$HOME"
setenv -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.config/tmux/plugins/"
if "test ! -d $HOME/.config/tmux/plugins/tpm" {
  run 'mkdir -p $HOME/.config/tmux/plugins &&
    git clone https://github.com/tmux-plugins/tpm $HOME/.config/tmux/plugins/tpm &&
    $HOME/.config/tmux/plugins/tpm/bin/install_plugins'
}

# plugin manager
set -g @plugin 'tmux-plugins/tpm'

# # tmux-suspend
# set -g @plugin 'xavierchanth/tmux-suspend'
# set -g @suspend_key 'M-z'
# set -g @suspend_on_suspend_command "tmux rename-session '#S 🔒'"
# set -g @suspend_on_resume_command "tmux rename-session \"$(tmux display-message -p '#S' | sed 's/ 🔒$//')\" "

# tmux session persistence
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @resurrect-capture-pane-contents 'on'
#
# set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @contiuum-restore 'on'
#
# set -g @plugin 'xavierchanth/tmux-fzf-url'
# set -g @fzf-url-bind 'u'
# set -g @fzf-url-extra-filter 'rg -o (https?):\/\/.*[^>]*'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run "$HOME/.config/tmux/plugins/tpm/tpm"
