{
  lib,
  pkgs,
  ...
}: let
  tmuxPlugins = with pkgs.tmuxPlugins; [
    minimal-tmux-status
  ];
in {
  xdg.configFile."tmux/plugins.conf".text = ''
    # generated by Home Manager
    ${lib.concatMapStringsSep "\n" (plugin: "run-shell ${plugin.rtp}") tmuxPlugins}
  '';
}
