git: 
  mainBranches: [main, master, trunk]
  paging:
    colorArg: always
    pager: delta --dark --paging=never --syntax-theme base16-256 -s
# confirmOnQuit: true
customCommands:
  - key: 'N'
    context: 'localBranches'
    prompts:
      - type: 'input'
        title: 'What is the new branch name?'
        key: 'BranchName'
        initialValue: ''
    command: "git branch {{.Form.BranchName}} {{.SelectedLocalBranch.Name}}"
    loadingText: 'Creating branch'
gui:
  filterMode: fuzzy 
  nerdFontsVersion: "3"
# catppuccin mocha-blue
  theme:
    activeBorderColor:
      - '#89b4fa'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#89b4fa'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'

  authorColors:
    '*': '#b4befe'

