git:
  mainBranches: [main, master, trunk]
  paging:
    colorArg: always
    pager: delta --dark --paging=never --syntax-theme base16-256 -s

customCommands:
  - key: "N"
    context: "localBranches"
    prompts:
      - type: "input"
        title: "What is the new branch name?"
        key: "BranchName"
        initialValue: ""
    command: "git branch {{.Form.BranchName}} {{.SelectedLocalBranch.Name}}"
    loadingText: "Creating branch"

gui:
  filterMode: fuzzy
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - bold
  authorColors:
    "*": "cyan"

keybinding:
  universal:
    prevBlock-alt: ""
    nextBlock-alt: ""
    nextTab: l
    prevTab: h
