gui:
  filterMode: fuzzy 
  nerdFontsVersion: "3"
git: 
  mainBranches: [main, master, trunk]
  paging:
    colorArg: always
    pager: delta --dark --paging=never --syntax-theme base16-256 -s
# confirmOnQuit: true
