
# reload configuration key bind
unbind r
bind -r r source "$HOME/.config/tmux/tmux.conf"

# use C-space as the prefix
set -g prefix C-space
bind C-space send-prefix

# general settings
set -g mouse on
set -g history-limit 25000
set -g status-position top

# from tmux-sensible
set -g focus-events on
set -g automatic-rename on
setw -g aggressive-resize on

# nvim qol
set -sg escape-time 0
set -g detach-on-destroy off

# count the panes from 1
set -g base-index 1
set -g renumber-windows on
setw -g pane-base-index 1

