# session management
bind a popup -w 85% -h 85% -E "~/.local/bin/fzf_session" # fzf add session
bind s run -C 'choose-tree -s -O time; send j' # open choose-tree sorted by recency, with previous pane selected
# https://unix.stackexchange.com/questions/759401/is-there-a-way-to-customize-the-keys-in-tmuxs-choose-mode
bind -T root a if-shell -F '#{==:#{pane_mode},tree-mode}' { 
  popup -w 85% -h 85% -E '~/.local/bin/fzf_session'
}{
  send a
}
bind -T root s if-shell -F '#{==:#{pane_mode},tree-mode}' "popup -w 85% -h 85% -E '~/.local/bin/fzf_ssh_session'" 'send s'
bind -T root n if-shell -F '#{==:#{pane_mode},tree-mode}' "popup -w 85% -h 85% -E '~/.local/bin/mkproj'" 'send n'
bind -T root d if-shell -F '#{==:#{pane_mode},tree-mode}' 'send x' 'send d'

# layouts
bind l popup -w 85% -h 85% -E 'source ~/.config/tmux/scripts/layout.sh && fzf_layout'


