source "$HOME/.config/tmux/env.conf"
source "$HOME/.config/tmux/opts.conf"
source "$HOME/.config/tmux/vim.conf"
source "$HOME/.config/tmux/keymaps.conf"
source "$HOME/.config/tmux/history.conf"
source "$HOME/.config/tmux/alerts.conf"
source "$HOME/.config/tmux/plugins.conf"
source "$HOME/.config/tmux/server.conf"

# theme must be loaded after plugins.conf
source "$HOME/.config/tmux/theme.conf"
