"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "xavierchanth"
email = "xchanthavong@gmail.com"

[[--scope]]
--when.repositories = ["~/src/af/", "~/src/ac/"]
[--scope.user]
email = "xavier@atsign.com"

[[--scope]]
--when.repositories = ["~/src/ws/"]
[--scope.user]
email = "xavier@woosah.io"

[[--scope]]
--when.repositories = ["~/src/cc/"]
[--scope.user]
email = "xavier@chanthvongconsulting.ca"

[ui]
default-command = "log"

conflict-marker-style = "snapshot"
# conflict-marker-style = "diff" # shows +/- at start of line

diff-formatter = "difft"
diff-editor = ":builtin"
merge-editor = "nvim"

[merge-tools.delta]
diff-args=[
  "--paging=always",
  "--file-transformation", 's\^.*(left|right)/\\\',
  "$left", "$right",
]
diff-expected-exit-codes = [0, 1]

[merge-tools.difft]
diff-args = ["--color=always", "--display=inline", "$left", "$right"]

[merge-tools.nvim]
diff-invocation-mode = "file-by-file"
edit-args = ["-d", "-o", "$left", "$right"]
merge-args = [
  "-f", "-d", "$output",
  "-M", "$left", "$base", "$right",
  "-c", "wincmd J",
  "-c", "set modifiable",
  "-c", "set write",
  "-c", "set wrap",
  "-c", "lua require('persistence').stop()",
]
merge-tool-edits-conflict-markers = true

[merge-tools.vimdiff]
diff-invocation-mode = "file-by-file"

# [revsets]
# short-prefixes = "(trunk..@)::"

[snapshot]
max-new-file-size = "10MiB"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519.pub"

[git]
private-commits = "description(glob:'wip:*') | description(glob:'private:*')"
track-default-bookmark-on-clone = true

[aliases]
e = ["edit"]
gp = ["git", "push"]
gf = ["git", "fetch"]
ls = ["diff", "-s"]
difft = ["diff", "--tool", "difft"]
delta = ["diff", "--tool", "delta"]
nt = ["new", "trunk()"]

bs = ["bookmark", "set"]
bm = ["bookmark", "move"]
bf = ["bookmark", "forget"]
bl = ["bookmark", "list"]
blt = ["bookmark", "list", "--tracked"]
bla = ["bookmark", "list", "--all-remotes"]
blr = ["bookmark", "list", "--remote"]

w = ["workspace"]
wa = ["workspace", "add"]
wl = ["workspace", "list"]
wr = ["workspace", "rename"]
wf = ["workspace", "forget"]

heads = ["branch"]
sp = ["split"]
sq = ["squash"]
colocate =  ["util", "exec", "--", "/bin/sh", "-c", """
#!/usr/bin/env bash
set -eux
  [ -d ".git" ] && {
    echo The .git dir already exists
    exit 0
  }
  echo '/*' > .jj/.gitignore
  mv .jj/repo/store/git .git
  echo -n '../../../.git' > .jj/repo/store/git_target
  git config --unset core.bare
  jj new
  jj undo
""", ""]

# Rebase from origin
# i.e. Separate local changes from the commit on origin and move them to a new
#      changeset.
ro = ["util", "exec", "--", "/bin/sh", "-c", """
#!/usr/bin/env bash
set -ex
  remote="origin"
  if [ -n "$2" ]; then
    remote="$2"
  fi
  jj new $1@$remote
  bookmarks=$(jj bookmark list -r $1 -T 'if(remote == "", name ++ " ")')
  jj restore --from $1
  jj abandon $1
  jj bookmark set --allow-backwards -r "@-" $bookmarks
  jj bookmark set $1
""", ""]

review = ["util", "exec", "--", "/bin/sh", "-c", """
#!/usr/bin/env bash
set -eux
  jj new trunk()
  jj git fetch
  gh pr checkout $1
  jj diff --from trunk() --to @-
""", ""]

logg = ["llog"]
llog = [
  "log",
  "-r",
  "ancestors(@, 200)",
  "--color=always",
  "--config",
  "template-aliases.'format_timestamp(timestamp)'='timestamp.format(\"%H:%M %D\")'",
  "--template",
  "narrow_log_comfortable"
]

log-watch = [
  "log",
  "--color=always",
  "--config",
  "template-aliases.'format_timestamp(timestamp)'='timestamp.format(\"%H:%M %D\")'",
  "--template",
  "narrow_log_comfortable",
  "-r",
  "brief",
]

branch = [ "log", "-r", "bookmarks()" ]

[revset-aliases]
"immutable_heads()" = "builtin_immutable_heads() | (trunk().. & ~mine())"
'working(x)' = "x+ & mine() & mutable()"
'w(x)' = 'working(x)'
'brief' = 'bookmarks() & ~immutable() | tracked_remote_bookmarks() | reachable(@, trunk()..)'

[templates]
log = 'builtin_log_comfortable'
git_push_bookmark = '"xc-" ++ change_id.short()'

[template-aliases]
'format_timestamp(timestamp)' = 'rel_time(timestamp)'
'full_time(timestamp)' = 'timestamp'
'short_time(timestamp)' = 'timestamp.format("%H:%M %D")'
'rel_time(timestamp)' = 'timestamp.ago()'
'format_short_signature(signature)' = 'signature.name()'

# Small number of columns available
'narrow_format_short_commit_header(commit)' = '''
  concat(
      separate(" ",
          format_short_change_id_with_change_offset(commit),
          format_short_signature(commit.author()),
          format_timestamp(commit.committer().timestamp()),
      ) ++ "\n",
      separate(" ",
      commit.bookmarks(),
          commit.tags(),
          commit.working_copies(),
          if(commit.contained_in('first_parent(@)'), label("git_head", "git_head()")),
          format_short_commit_id(commit.commit_id()),
          if(commit.conflict(), label("conflict", "conflict")),
      )
  )
'''

narrow_log_compact = '''
if(root,
  format_root_commit(self),
  label(if(current_working_copy, "working_copy"),
    concat(
      narrow_format_short_commit_header(self) ++ "\n",
      separate(" ",
        if(empty, label("empty", "(empty)")),
        if(description,
          description.first_line(),
          label(if(empty, "empty"), description_placeholder),
        ),
      ) ++ "\n",
    ),
  )
)
'''

narrow_log_comfortable = 'narrow_log_compact ++ "\n"'
