{
  lib,
  pkgs,
  ...
}: let
  tmuxScriptTree = pkgs.runCommandLocal "tmux-helper-scripts" {} ''
    mkdir -p "$out/bin"

    cp ${./tmux-scripts/add_session.sh} "$out/bin/add_session.sh"
    cp ${./tmux-scripts/fzf_session} "$out/bin/fzf_session"
    cp ${./tmux-scripts/fzf_jj_session} "$out/bin/fzf_jj_session"
    cp ${./tmux-scripts/fzf_ssh_session} "$out/bin/fzf_ssh_session"
    cp ${./tmux-scripts/jj-term} "$out/bin/jj-term"
    cp ${./tmux-scripts/jj-term-cleanup} "$out/bin/jj-term-cleanup"
    cp ${./tmux-scripts/merge_history} "$out/bin/merge_history"

    chmod 755 \
      "$out/bin/add_session.sh" \
      "$out/bin/fzf_session" \
      "$out/bin/fzf_jj_session" \
      "$out/bin/fzf_ssh_session" \
      "$out/bin/jj-term" \
      "$out/bin/jj-term-cleanup" \
      "$out/bin/merge_history"
  '';

  mkTmuxHelper = {
    name,
    runtimeInputs ? [],
  }:
    pkgs.writeShellApplication {
      inherit name;
      runtimeInputs = [pkgs.bash] ++ runtimeInputs;
      text = ''
        exec ${tmuxScriptTree}/bin/${name} "$@"
      '';
    };

  fzfSession = mkTmuxHelper {
    name = "fzf_session";
    runtimeInputs = with pkgs; [fzf tmux];
  };

  fzfJjSession = mkTmuxHelper {
    name = "fzf_jj_session";
    runtimeInputs = with pkgs; [fzf jujutsu tmux];
  };

  fzfSshSession = mkTmuxHelper {
    name = "fzf_ssh_session";
    runtimeInputs = with pkgs; [fzf openssh ripgrep tmux];
  };

  jjTermCleanup = mkTmuxHelper {
    name = "jj-term-cleanup";
    runtimeInputs = with pkgs; [gnugrep tmux];
  };

  jjTerm = mkTmuxHelper {
    name = "jj-term";
    runtimeInputs = with pkgs; [git tmux];
  };

  mergeHistory = mkTmuxHelper {
    name = "merge_history";
    runtimeInputs = with pkgs; [coreutils];
  };

  tmuxPlugins = with pkgs.tmuxPlugins; [
    minimal-tmux-status
  ];
in {
  home.packages = [
    fzfJjSession
    fzfSession
    fzfSshSession
    jjTerm
    jjTermCleanup
    mergeHistory
  ];

  xdg.configFile."tmux/keymaps.conf".text = ''
    # vim:set ft=tmux:
    # session management
    bind a popup -w 85% -h 85% -E "${lib.getExe fzfSession}"
    bind s run -C 'choose-tree -s -O time; send j' # custom choose-tree

    bind -T root a if-shell -F '#{==:#{pane_mode},tree-mode}' {
      popup -w 85% -h 85% -E '${lib.getExe fzfSession}'
    }{
      send a
    }
    bind -T root s if-shell -F '#{==:#{pane_mode},tree-mode}' {
      popup -w 85% -h 85% -E '${lib.getExe fzfSshSession}'
    }{
      send s
    }

    # Layouts
    bind e selectl -E;
    bind g run '${lib.getExe jjTerm}'
  '';

  xdg.configFile."tmux/history.conf".text = ''
    # vim:set ft=tmux:
    # history management
    %hidden zsh_state="$HOME/.local/state/zsh"
    %hidden history_dir="$zsh_state/history"
    %hidden main_hist_file="$zsh_state/main_history"
    %hidden last_hist_file="$zsh_state/tmux_history_cache"
    set-hook -g session-created {
      setenv -Fh hist_file "$history_dir/#{hook_session_name}"
      run "bash -c \"cat $last_hist_file | sed -e 's/^#{hook_session_name}=.*\$//g' >$last_hist_file\"" # wipe old entry
      run "echo '#{hook_session_name}=#(tac $main_hist_file | rg -m 1 '.')' >>$last_hist_file" # add new entry
      run "cp -f $main_hist_file '$history_dir/#{hook_session_name}'"; # setup tmux hist file
    }

    set-hook -g session-closed {
      run "${lib.getExe mergeHistory} $history_dir/#{hook_session_name} $main_hist_file"
    }
  '';

  xdg.configFile."tmux/plugins.conf".text = ''
    # generated by Home Manager
    ${lib.concatMapStringsSep "\n" (plugin: "run-shell ${plugin.rtp}") tmuxPlugins}
  '';
}
