start-at-login = true

after-startup-command = [
  'exec-and-forget /opt/homebrew/opt/sketchybar/bin/sketchybar',
]

exec-on-workspace-change = ['/bin/bash', '-c',
  '/opt/homebrew/opt/sketchybar/bin/sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]

[gaps]
# inner.horizontal = 8
# inner.vertical =   8
# outer.left =       8
# outer.bottom =     8
# outer.top =        [ {monitor.built-in = 8}, 48]
# outer.right =      8

inner.horizontal = 0
inner.vertical =   0
outer.left =       0
outer.bottom =     0
outer.top =        [ {monitor.built-in = 0}, {monitor.main = 40}, 0]
outer.right =      0

[workspace-to-monitor-force-assignment]
1 = 'secondary'

# See https://nikitabobko.github.io/AeroSpace/guide#exec-env-vars
[exec]
inherit-env-vars = true
[exec.env-vars]
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[[on-window-detected]] # Don't tile the floating iterm2 window
if.app-id = 'com.googlecode.iterm2'
if.window-title-regex-substring = '^Floating Terminal$'
run = "layout floating"

[[on-window-detected]] # "Waiting for host" window on zoom
if.app-id = 'us.zoom.xos'
if.window-title-regex-substring = '^$' # good job, not implementing the accessibility APIs AND not giving the window a name zoom!
run = "layout floating"

[[on-window-detected]] # Don't tile the floating iterm2 window
if.app-name-regex-substring = '^LibreWolf$|^Firefox$'
if.window-title-regex-substring = '^Picture-in-Picture$'
run = "layout floating"

# Startup layout
[[on-window-detected]]
if.app-name-regex-substring ='.'
if.during-aerospace-startup = true
check-further-callbacks=true
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-name-regex-substring = '^LibreWolf$|^Firefox$'
if.during-aerospace-startup = true
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-name-regex-substring = '^alacritty$|^WezTerm$|^wezterm-gui$'
if.during-aerospace-startup = true
run = 'move-node-to-workspace 3'

[mode.main.binding]
alt-shift-r = [
  'exec-and-forget aerospace reload-config',
  'exec-and-forget /opt/homebrew/opt/sketchybar/bin/sketchybar --reload'
]

alt-enter = ['exec-and-forget wezterm']
alt-shift-enter = ['exec-and-forget wezterm start zsh']

# Layout movement
alt-s = 'layout tiles horizontal vertical'
alt-a = 'layout accordion horizontal vertical'

alt-shift-space = 'layout floating tiling'

alt-f = 'fullscreen'
alt-shift-f = 'macos-native-fullscreen'

# Window movement
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Workspace movement
alt-tab = 'workspace-back-and-forth'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9']

# Resizing
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

