#!/bin/sh

# QUTE_MODE: Either hints (started via hints) or command (started via command or key binding).
# QUTE_USER_AGENT: The currently set user agent, if customized.
# QUTE_FIFO: The FIFO or file to write commands to.
# QUTE_HTML: Path of a file containing the HTML source of the current page.
# QUTE_TEXT: Path of a file containing the plaintext of the current page.
# QUTE_CONFIG_DIR: Path of the directory containing qutebrowser’s configuration.
# QUTE_DATA_DIR: Path of the directory containing qutebrowser’s data.
# QUTE_DOWNLOAD_DIR: Path of the downloads directory.
# QUTE_COMMANDLINE_TEXT: Text currently in qutebrowser’s command line. Note this is only useful for userscripts spawned (e.g. via a keybinding) when qutebrowser is still in command mode. If you want to receive arguments passed to your userscript via :spawn, use the normal way of getting commandline arguments (e.g. $@ in bash or sys.argv / argparse / …​ in Python).
# QUTE_VERSION: The version of qutebrowser, as a string like "2.0.0". Note that this was added in v2.0.0, thus older versions can only be detected by the absence of this variable.

# TODO: make bitwarden plugin
