SPACE cycle pause; show-text "${filename} \n${time-remaining}"
k     cycle pause; show-text "${filename} \n${time-remaining}"
j     seek -5
l     seek  5

w-q   quit-watch-later 0
q     quit             0

h      cycle fullscreen
n      cycle sub
m      cycle mute
DOWN   add   volume -2
UP     add   volume  2
LEFT   add   speed  -0.25
RIGHT  add   speed   0.25
0      set   speed   1.0
