start-at-login = true

after-startup-command = [
    'exec-and-forget /opt/homebrew/opt/borders/bin/borders active_color=0xffff5c35 inactive_color=0x00000000 style=round width=5.0 blur_radius=5.0'
]

[gaps]
inner.horizontal = 8
inner.vertical =   8
outer.left =       8
outer.bottom =     8
outer.top =        8
outer.right =      8

# See https://nikitabobko.github.io/AeroSpace/guide#exec-env-vars
[exec]
inherit-env-vars = true
[exec.env-vars]
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[[on-window-detected]] # Don't tile the floating iterm2 window
if.app-id = 'com.googlecode.iterm2'
if.window-title-regex-substring = '^Floating Terminal$'
run = "layout floating"

[mode.main.binding]
alt-shift-r = 'reload-config'
alt-enter = ['exec-and-forget alacritty msg create-window || alacritty']

# Layout movement
alt-s = 'layout tiles horizontal vertical'
alt-a = 'layout accordion horizontal vertical'
alt-f = 'fullscreen'
alt-shift-space = 'layout floating tiling'

# Window movement
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Workspace movement
alt-tab = 'workspace-back-and-forth'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9']

# Resizing
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'
# alt-r = 'mode resize'
# [mode.resize.binding]
# h = 'resize width -50'
# j = 'resize height +50'
# k = 'resize height -50'
# l = 'resize width +50'
# enter = 'mode main'
# esc = 'mode main'
