[user]
name = "XavierChanth"
email = "xchanthavong@gmail.com"

[ui]
default-command = "log"

conflict-marker-style = "snapshot"
# conflict-marker-style = "diff" # shows +/- at start of line

diff.tool = [
  "delta",
  "--paging=always",
  "--file-transformation", 's\^.*(left|right)/\\\',
  "$left", "$right",
]

diff-editor = ":builtin"
# diff-editor = "nvim"

# hunk.nvim plugin
[merge-tools.nvim]
program = "nvim"
edit-args = ["-c", "DiffEditor $left $right $output"]

# [revsets]
# short-prefixes = "(trunk..@)::"

[snapshot]
max-new-file-size = "10MiB"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519.pub"

[git]
auto-local-bookmark = false
push-bookmark-prefix = "xc-"
private-commits = "description(glob:'wip:*') | description(glob:'private:*')"
# subprocess = true

[aliases]
e = ["edit"]
gp = ["git", "push"]
gf = ["git", "fetch"]
bs = ["bookmark", "set"]
bm = ["bookmark", "move"]
bf = ["bookmark", "forget"]
ls = ["diff", "-s"]
sp = ["split"]
sq = ["squash"]
nt = ["new", "trunk"]

llog = [
  "log",
  "-r",
  "ancestors(@, 200)",
  "--color=always",
  "--config",
  "template-aliases.'format_timestamp(timestamp)'='timestamp.format(\"%H:%M %D\")'",
  "--template",
  "narrow_log_comfortable"
]

log-watch = [
  "log",
  "--color=always",
  "--config",
  "template-aliases.'format_timestamp(timestamp)'='timestamp.format(\"%H:%M %D\")'",
  "--template",
  "narrow_log_comfortable"
]

[revset-aliases]
'working(x)' = "all:x+ & mine()"
'w(x)' = 'working(x)'

[templates]
log = 'builtin_log_comfortable'

[template-aliases]
'format_timestamp(timestamp)' = 'rel_time(timestamp)'
'full_time(timestamp)' = 'timestamp'
'short_time(timestamp)' = 'timestamp.format("%H:%M %D")'
'rel_time(timestamp)' = 'timestamp.ago()'
'format_short_signature(signature)' = 'signature.name()'

# Small number of columns available
'narrow_format_short_commit_header(commit)' = '''
  concat(
      separate(" ",
          format_short_change_id_with_hidden_and_divergent_info(commit),
          format_short_signature(commit.author()),
          format_timestamp(commit.committer().timestamp()),
      ) ++ "\n",
      separate(" ",
      commit.bookmarks(),
          commit.tags(),
          commit.working_copies(),
          if(commit.git_head(), label("git_head", "git_head()")),
          format_short_commit_id(commit.commit_id()),
          if(commit.conflict(), label("conflict", "conflict")),
      )
  )
'''

narrow_log_compact = '''
if(root,
  format_root_commit(self),
  label(if(current_working_copy, "working_copy"),
    concat(
      narrow_format_short_commit_header(self) ++ "\n",
      separate(" ",
        if(empty, label("empty", "(empty)")),
        if(description,
          description.first_line(),
          label(if(empty, "empty"), description_placeholder),
        ),
      ) ++ "\n",
    ),
  )
)
'''

narrow_log_comfortable = 'narrow_log_compact ++ "\n"'
