[settings]
paranoid = true
disable_backends = ["asdf", "vfox"]
minimum_release_age = "3d"
lockfile = false

[tools]
rust = { version = "stable", profile = "minimal", components = "cargo,clippy,rustc,rustfmt,rust-analyzer", targets = "wasm32-unknown-unknown" }
node = "lts"
bun = "latest"
go = "latest"
python = "latest"
ruby = "latest"
zig = "latest"
# dart = "latest" # Optional; Flutter currently supplies Dart.

"npm:pnpm" = "latest"
"npm:prettier" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:@microsoft/compose-language-service" = "latest"
"npm:svelte-language-server" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:yaml-language-server" = "latest"
"pipx:basedpyright" = "latest"
"pipx:ruff" = "latest"
"pipx:uv" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:mvdan.cc/gofumpt" = "latest"
"go:mvdan.cc/sh/v3/cmd/shfmt" = "latest"
"cargo:neocmakelsp" = "latest"
"cargo:sccache" = "latest"
"cargo:stylua" = "latest"
"cargo:tinymist" = "latest"
"cargo:tombi-cli" = "latest"
"cargo:typst-cli" = "latest"
"aqua:hadolint/hadolint" = "latest"
"aqua:LuaLS/lua-language-server" = "latest"
"aqua:koalaman/shellcheck" = "latest"
"aqua:cue-lang/cue" = "latest"
"aqua:zigtools/zls" = "latest"
