#!/usr/bin/env lua

os.execute(
	"[ ! -d $HOME/.local/share/sketchybar_lua/ ] && "
		.. "(git clone https://github.com/FelixKratz/SbarLua.git /tmp/SbarLua && cd /tmp/SbarLua/ && make install)"
)

package.cpath = package.cpath .. ";" .. os.getenv("HOME") .. "/.local/share/sketchybar_lua/?.so"

local sbar = require("sketchybar")

sbar.begin_config()

require("init")

sbar.hotload(true)
sbar.end_config()

sbar.exec("aerospace list-windows --focused", function(window)
	sbar.trigger("front_app_switched", {
		INFO = window:match("| (.*) |"),
	})
end)
sbar.exec("aerospace list-workspaces --focused", function(workspace)
	sbar.trigger("aerospace_workspace_change", {
		FOCUSED_WORKSPACE = workspace,
	})
end)

sbar.event_loop()
