#!/bin/sh
case "$XDG_CURRENT_DESKTOP" in
sway) source $HOME/.config/env/sway ;;
Hyprland) source $HOME/.config/env/hyprland ;;
gnome) source $HOME/.config/env/gnome ;;
esac

case "$(uname)" in
daedalus)
  source $HOME/.config/env/framework
  ;;
esac

command -v sway >/dev/null 2>&1 && [ "$(tty)" = "/dev/tty1" ] && {
  source $HOME/.config/env/sway
  exec sway
}

command -v gnome-shell >/dev/null 2>&1 && [ "$(tty)" = "/dev/tty2" ] && {
  source $HOME/.config/env/gnome
  exec gnome-shell
}

command -v Hyprland >/dev/null 2>&1 && [ "$(tty)" = "/dev/tty3" ] && {
  source $HOME/.config/env/hyprland
  exec Hyprland
}

# idk... niri doesn't seem like a good improvement to my workflow
# The sway workflow is so natural at this point
# command -v niri >/dev/null 2>&1 && [ "$(tty)" = "/dev/tty3" ] && {
#   source $HOME/.config/env/niri
#   if [ "$(uname)" = 'daedalus' ]; then
#     source $HOME/.config/env/framework
#   fi
#   dbus-run-session niri
# }
