FROM ubuntu:latest

RUN apt-get update;
RUN apt-get install -y git;
RUN apt-get install -y sudo;
RUN apt-get install -y curl;
RUN apt-get install -y cron;
RUN apt-get install -y tmux;
RUN apt-get install -y ripgrep;
RUN apt-get install -y vim;

