# My preferred power button for sway:
# I want wlogout to handle power key, and long press to force poweroff
# This file needs to be renamed before it takes effect, I try to avoid
# modifying anything that will effect other sessions without some manual
# intervention
[Login]
HandlePowerKey=ignore
HandlePowerKeyLongPress=poweroff
IdleAction=suspend
KillUserProcesses=no
