# vim:set ft=tmux:
# history management
%hidden zsh_state="$HOME/.local/state/zsh"
%hidden history_dir="$zsh_state/history"
%hidden main_hist_file="$zsh_state/main_history"
%hidden last_hist_file="$zsh_state/tmux_history_cache"
set-hook -g session-created {
  setenv -Fh hist_file "$history_dir/#{hook_session_name}"
  run "bash -c \"cat $last_hist_file | sed -e 's/^#{hook_session_name}=.*\$//g' >$last_hist_file\"" # wipe old entry
  run "echo '#{hook_session_name}=#(tac $main_hist_file | rg -m 1 '.')' >>$last_hist_file" # add new entry
  run "cp -f $main_hist_file '$history_dir/#{hook_session_name}'"; # setup tmux hist file
}

set-hook -g session-closed {
  run "$HOME/.local/bin/merge_history $history_dir/#{hook_session_name} $main_hist_file"
}
